on:
  pull_request:
    branches:
      - master
    types: [synchronize, closed]

jobs:
  contributify_bot:
    runs-on: ubuntu-latest
    name: A Job which adds Contributors
    steps:
      - name: Contributify BOT
        uses: r4pt0s/contributify@master
